// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPDFTranslation() {
  return window['go']['main']['App']['CancelPDFTranslation']();
}

export function CancelProcess() {
  return window['go']['main']['App']['CancelProcess']();
}

export function CheckExistingTranslation(arg1) {
  return window['go']['main']['App']['CheckExistingTranslation'](arg1);
}

export function CheckShareStatus() {
  return window['go']['main']['App']['CheckShareStatus']();
}

export function CheckShareStatusForPaper(arg1) {
  return window['go']['main']['App']['CheckShareStatusForPaper'](arg1);
}

export function CheckStartupRequirements() {
  return window['go']['main']['App']['CheckStartupRequirements']();
}

export function ClearAllErrors() {
  return window['go']['main']['App']['ClearAllErrors']();
}

export function ClearError(arg1) {
  return window['go']['main']['App']['ClearError'](arg1);
}

export function ContinueTranslation(arg1) {
  return window['go']['main']['App']['ContinueTranslation'](arg1);
}

export function DeleteTranslatedPaper(arg1) {
  return window['go']['main']['App']['DeleteTranslatedPaper'](arg1);
}

export function DownloadBilingualPDF() {
  return window['go']['main']['App']['DownloadBilingualPDF']();
}

export function DownloadChinesePDF() {
  return window['go']['main']['App']['DownloadChinesePDF']();
}

export function DownloadGitHubTranslation(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadGitHubTranslation'](arg1, arg2, arg3);
}

export function DownloadLatexZip() {
  return window['go']['main']['App']['DownloadLatexZip']();
}

export function EnsureGitHubToken() {
  return window['go']['main']['App']['EnsureGitHubToken']();
}

export function ExportErrorIDsToFile() {
  return window['go']['main']['App']['ExportErrorIDsToFile']();
}

export function ExportErrorsToFile() {
  return window['go']['main']['App']['ExportErrorsToFile']();
}

export function FetchAndDecodeGitHubToken() {
  return window['go']['main']['App']['FetchAndDecodeGitHubToken']();
}

export function GetArxivPaperMetadata(arg1) {
  return window['go']['main']['App']['GetArxivPaperMetadata'](arg1);
}

export function GetCompiler() {
  return window['go']['main']['App']['GetCompiler']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloader() {
  return window['go']['main']['App']['GetDownloader']();
}

export function GetLaTeXDownloadURL() {
  return window['go']['main']['App']['GetLaTeXDownloadURL']();
}

export function GetLastInput() {
  return window['go']['main']['App']['GetLastInput']();
}

export function GetPDFDataURL(arg1) {
  return window['go']['main']['App']['GetPDFDataURL'](arg1);
}

export function GetPDFStatus() {
  return window['go']['main']['App']['GetPDFStatus']();
}

export function GetResultsDirectory() {
  return window['go']['main']['App']['GetResultsDirectory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTranslatedPDFPath() {
  return window['go']['main']['App']['GetTranslatedPDFPath']();
}

export function GetTranslator() {
  return window['go']['main']['App']['GetTranslator']();
}

export function GetValidator() {
  return window['go']['main']['App']['GetValidator']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function IsProcessing() {
  return window['go']['main']['App']['IsProcessing']();
}

export function ListErrors() {
  return window['go']['main']['App']['ListErrors']();
}

export function ListRecentGitHubTranslations(arg1) {
  return window['go']['main']['App']['ListRecentGitHubTranslations'](arg1);
}

export function ListTranslatedPapers() {
  return window['go']['main']['App']['ListTranslatedPapers']();
}

export function LoadPDF(arg1) {
  return window['go']['main']['App']['LoadPDF'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenPDFFileDialog() {
  return window['go']['main']['App']['OpenPDFFileDialog']();
}

export function OpenPDFInSystem(arg1) {
  return window['go']['main']['App']['OpenPDFInSystem'](arg1);
}

export function OpenPaperResult(arg1) {
  return window['go']['main']['App']['OpenPaperResult'](arg1);
}

export function OpenURLInBrowser(arg1) {
  return window['go']['main']['App']['OpenURLInBrowser'](arg1);
}

export function ProcessSource(arg1) {
  return window['go']['main']['App']['ProcessSource'](arg1);
}

export function ProcessSourceWithForce(arg1, arg2) {
  return window['go']['main']['App']['ProcessSourceWithForce'](arg1, arg2);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RetranslateFromArxiv(arg1) {
  return window['go']['main']['App']['RetranslateFromArxiv'](arg1);
}

export function RetryFromError(arg1) {
  return window['go']['main']['App']['RetryFromError'](arg1);
}

export function SaveLastInput(arg1) {
  return window['go']['main']['App']['SaveLastInput'](arg1);
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function SearchGitHubTranslation(arg1) {
  return window['go']['main']['App']['SearchGitHubTranslation'](arg1);
}

export function SetStatusCallback(arg1) {
  return window['go']['main']['App']['SetStatusCallback'](arg1);
}

export function SetWailsRuntime(arg1) {
  return window['go']['main']['App']['SetWailsRuntime'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}

export function SharePaperToGitHub(arg1, arg2, arg3) {
  return window['go']['main']['App']['SharePaperToGitHub'](arg1, arg2, arg3);
}

export function ShareToGitHub(arg1, arg2) {
  return window['go']['main']['App']['ShareToGitHub'](arg1, arg2);
}

export function TestAPIConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestAPIConnection'](arg1, arg2, arg3);
}

export function TestGitHubConnection(arg1) {
  return window['go']['main']['App']['TestGitHubConnection'](arg1);
}

export function TranslatePDF() {
  return window['go']['main']['App']['TranslatePDF']();
}

export function UpdateGitHubToken() {
  return window['go']['main']['App']['UpdateGitHubToken']();
}
