// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {results} from '../models';
import {main} from '../models';
import {types} from '../models';
import {compiler} from '../models';
import {config} from '../models';
import {downloader} from '../models';
import {pdf} from '../models';
import {translator} from '../models';
import {validator} from '../models';
import {errors} from '../models';
import {github} from '../models';

export function CancelPDFTranslation():Promise<void>;

export function CancelProcess():Promise<void>;

export function CheckExistingTranslation(arg1:string):Promise<results.ExistingTranslationInfo>;

export function CheckShareStatus():Promise<main.ShareCheckResult>;

export function CheckShareStatusForPaper(arg1:string):Promise<main.ShareCheckResult>;

export function CheckShareStatusWithCategory(arg1:string):Promise<main.ShareCheckResult>;

export function CheckStartupRequirements():Promise<main.StartupCheckResult>;

export function ClearAllErrors():Promise<void>;

export function ClearError(arg1:string):Promise<void>;

export function ContinueTranslation(arg1:string):Promise<types.ProcessResult>;

export function DeleteTranslatedPaper(arg1:string):Promise<void>;

export function DownloadBilingualPDF():Promise<string>;

export function DownloadChinesePDF():Promise<string>;

export function DownloadGitHubTranslation(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadLatexZip():Promise<string>;

export function EnsureGitHubToken():Promise<void>;

export function ExportErrorIDsToFile():Promise<string>;

export function ExportErrorsToFile():Promise<string>;

export function FetchAndDecodeGitHubToken():Promise<string>;

export function GetArxivPaperMetadata(arg1:string):Promise<main.ArxivPaperMetadata>;

export function GetCompiler():Promise<compiler.LaTeXCompiler>;

export function GetConfig():Promise<config.ConfigManager>;

export function GetDownloader():Promise<downloader.SourceDownloader>;

export function GetLaTeXDownloadURL():Promise<string>;

export function GetLastInput():Promise<string>;

export function GetPDFDataURL(arg1:string):Promise<string>;

export function GetPDFStatus():Promise<pdf.PDFStatus>;

export function GetPaperCategories():Promise<Array<types.PaperCategory>>;

export function GetResultsDirectory():Promise<string>;

export function GetSettings():Promise<types.Config>;

export function GetStatus():Promise<types.Status>;

export function GetTranslatedPDFPath():Promise<string>;

export function GetTranslator():Promise<translator.TranslationEngine>;

export function GetValidator():Promise<validator.SyntaxValidator>;

export function GetWorkDir():Promise<string>;

export function IsProcessing():Promise<boolean>;

export function ListErrors():Promise<Array<errors.ErrorRecord>>;

export function ListGitHubTranslationsByCategories(arg1:Array<string>,arg2:number):Promise<Array<github.ArxivPaperInfo>>;

export function ListRecentGitHubTranslations(arg1:number):Promise<Array<github.ArxivPaperInfo>>;

export function ListTranslatedPapers():Promise<Array<main.PaperListItem>>;

export function LoadPDF(arg1:string):Promise<pdf.PDFInfo>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenPDFFileDialog():Promise<string>;

export function OpenPDFInSystem(arg1:string):Promise<void>;

export function OpenPaperResult(arg1:string):Promise<types.ProcessResult>;

export function OpenURLInBrowser(arg1:string):Promise<void>;

export function ProcessSource(arg1:string):Promise<types.ProcessResult>;

export function ProcessSourceWithForce(arg1:string,arg2:boolean):Promise<types.ProcessResult>;

export function ReloadConfig():Promise<void>;

export function ReportErrorsToGitHub():Promise<github.IssueCreateResult>;

export function RetranslateFromArxiv(arg1:string):Promise<types.ProcessResult>;

export function RetryFromError(arg1:string):Promise<types.ProcessResult>;

export function SaveLastInput(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:number,arg8:string,arg9:string,arg10:string,arg11:number,arg12:boolean):Promise<void>;

export function SearchGitHubTranslation(arg1:string):Promise<github.TranslationSearchResult>;

export function SetStatusCallback(arg1:main.StatusCallback):Promise<void>;

export function SetWailsRuntime(arg1:boolean):Promise<void>;

export function SetWorkDir(arg1:string):Promise<void>;

export function SharePaperToGitHub(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<main.ShareResult>;

export function ShareToGitHub(arg1:string,arg2:boolean,arg3:boolean):Promise<main.ShareResult>;

export function TestAPIConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestGitHubConnection(arg1:string):Promise<void>;

export function TranslatePDF():Promise<pdf.TranslationResult>;

export function UpdateGitHubToken():Promise<void>;
